### ISSUE TITLE
Test Bluetooth Nodes and Android Phone RSSI Values in common positions to find proper placement of Nodes

### ISSUE THREAD

**Issue by fossij** [fossij/Monumap#9]
- [ ] #40

**Comment by arcec-cs** [comment]
Different android app library was used than planned that did not explicitly use RSSI values. Was not able to test nodes at school because of the shutdown of the school.

Will be moving the essence of this into sprint 2 where  I tweak and configure both the bluez(RPi) and  the Android Beacon Library to figure out the Region of beacons at my house for proof of concept.

for now binary testing of this has been shown by the demo app where it shows one if they are in the region or not.

See #47 for more info
